services:
  backend:
    container_name: e_shop
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8181:8181"
    env_file:
      - .env
    depends_on:
      - e-shop-bd
    environment:
        - SERVER_PORT= 8181
        - SPRING_DATASOURCE_URL=jdbc:postgresql://e-shop-bd:5432/e-shop



  e-shop-bd:
    image: "postgres:14.17"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
