spring:
  security:
    user:
      name: postgres
      password: password

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
      database: postgresql
      hibernate:
        ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: "test@gmail.com"
    password: "123"
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
  flyway:
    url: "jdbc:postgresql://e_shop_db:5432/e-shop"
    user: postgres
    password: password
    enabled: true
    locations: classpath:db.migration
    community-db-support-enabled: true
    clean-disabled: false
logging:
  level:
    # Логирование Flyway
    org.flywaydb: DEBUG
    # Логирование SQL-запросов
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.datasource.DataSourceTransactionManager: DEBUG
    # Логирование инициализации Spring Boot
    org.springframework.boot: DEBUG
    # Логирование подключения к БД
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
shop:
  jwt:
    secret:
      access: "M+9HLgODaHfqzPmg1IRQw+0R80q98WqwqrNysheVBy/fwSE2MaIlZ4fm74rrEbtX5n9cUf6GbGj/+deFKiDrDg=="
      refresh: "JkTtZdCbDJgE4ssjHV1bo8JACKTc6NybAGvHv4Cw5BnfhM3H8gp3736txkW1ZLG5ygUaxy2gCDkWw1rhYIR3DQ=="


