spring:
  security:
    user:
      name: postgres
      password: password
  datasource:
    url: jdbc:postgresql://localhost:5432/e-shop
    username: postgres
    password: password
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  token:
    signing:
      key: "53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855"  # ???? ? ????????
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    enabled: true
    locations: classpath:db.migration
shop:
  jwt:
    secret:
      access: "M+9HLgODaHfqzPmg1IRQw+0R80q98WqwqrNysheVBy/fwSE2MaIlZ4fm74rrEbtX5n9cUf6GbGj/+deFKiDrDg=="
      refresh: "JkTtZdCbDJgE4ssjHV1bo8JACKTc6NybAGvHv4Cw5BnfhM3H8gp3736txkW1ZLG5ygUaxy2gCDkWw1rhYIR3DQ=="
    expires:
      access-sec: 604800
      refresh-days: 30

