spring:
  security:
    user:
      name: postgres
      password: password
  datasource:
    url: jdbc:postgresql://localhost:5432/e-shop
    username: postgres
    password: password
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: "test@gmail.com"
    password: "123"
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    enabled: true
    locations: classpath:db.migration
shop:
  jwt:
    secret:
      access: "M+9HLgODaHfqzPmg1IRQw+0R80q98WqwqrNysheVBy/fwSE2MaIlZ4fm74rrEbtX5n9cUf6GbGj/+deFKiDrDg=="
      refresh: "JkTtZdCbDJgE4ssjHV1bo8JACKTc6NybAGvHv4Cw5BnfhM3H8gp3736txkW1ZLG5ygUaxy2gCDkWw1rhYIR3DQ=="
    expires:
      access-sec: 604800
      refresh-days: 30

