CREATE SEQUENCE IF NOT EXISTS bucket_sequence START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS buckets_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS category_sequence START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS item_sequence START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS refresh_token_token_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS user_sequence START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS users_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE buckets
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT,
    CONSTRAINT buckets_pkey PRIMARY KEY (id)
);

CREATE TABLE buckets_items
(
    bucket_id BIGINT NOT NULL,
    item_id   BIGINT NOT NULL,
    count integer NOT NULL
);

CREATE TABLE categories
(
    id   BIGINT NOT NULL,
    name VARCHAR(255),
    parent_category VARCHAR(255),
    CONSTRAINT categories_pkey PRIMARY KEY (id)
);

CREATE TABLE flyway_schema_history
(
    installed_rank INTEGER       NOT NULL,
    version        VARCHAR(50),
    description    VARCHAR(200)  NOT NULL,
    type           VARCHAR(20)   NOT NULL,
    script         VARCHAR(1000) NOT NULL,
    checksum       INTEGER,
    installed_by   VARCHAR(100)  NOT NULL,
    installed_on   TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    execution_time INTEGER       NOT NULL,
    success        BOOLEAN       NOT NULL,
    CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank)
);

CREATE TABLE items
(
    price       numeric(38, 2),
    id          BIGINT NOT NULL,
    count       VARCHAR(255),
    description VARCHAR(255),
    image       VARCHAR(255),
    title       VARCHAR(255),
    CONSTRAINT items_pkey PRIMARY KEY (id)
);

CREATE TABLE items_categories
(
    category_id        BIGINT NOT NULL,
    item_id            BIGINT NOT NULL,
    parent_category_id BIGINT NOT NULL,
    CONSTRAINT items_categories_pkey PRIMARY KEY (category_id, item_id)
);

CREATE TABLE refresh_token
(
    token_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id  BIGINT,
    token    VARCHAR(255),
    CONSTRAINT refresh_token_pkey PRIMARY KEY (token_id)
);

CREATE TABLE users
(
    bucket_id BIGINT,
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    address   VARCHAR(255),
    email     VARCHAR(255),
    password  VARCHAR(255),
    role      VARCHAR(255),
    username  VARCHAR(255),
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE buckets
    ADD CONSTRAINT buckets_user_id_key UNIQUE (user_id);

ALTER TABLE refresh_token
    ADD CONSTRAINT refresh_token_user_id_key UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT users_bucket_id_key UNIQUE (bucket_id);

CREATE INDEX flyway_schema_history_s_idx ON flyway_schema_history (success);

ALTER TABLE buckets_items
    ADD CONSTRAINT fk7272bsc9hv6m7k850ekia6f0w FOREIGN KEY (bucket_id) REFERENCES buckets (id) ON DELETE NO ACTION;

ALTER TABLE buckets_items
    ADD CONSTRAINT fk773jgk471xednobhr8ju3li49 FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE NO ACTION;

ALTER TABLE users
    ADD CONSTRAINT fk8l2qc4c6gihjdyoch727guci FOREIGN KEY (bucket_id) REFERENCES buckets (id) ON DELETE NO ACTION;

ALTER TABLE refresh_token
    ADD CONSTRAINT fkjtx87i0jvq2svedphegvdwcuy FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE buckets
    ADD CONSTRAINT fknl0ltaj67xhydcrfbq8401nvj FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;