CREATE TABLE photo (
    photo_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    picture_url VARCHAR(255),
    user_feedback_id BIGINT,
    PRIMARY KEY (photo_id),
    FOREIGN KEY (user_feedback_id) REFERENCES user_feedback(user_feedback_id)
);

CREATE INDEX idx_photo_user_feedback_id ON photo(user_feedback_id);